version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "src/bot.py"]
